development:
  adapter: mysql
  database: dropboxmusic_development
  username: root
  password:
  host: localhost

  
test:
  adapter: mysql
  database: dropboxmusic_test
  username: root
  password: 
  host: localhost
